# Generated by Django 4.2.3 on 2023-08-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documnet_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
